BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Cars" (
	"Id"	INTEGER NOT NULL,
	"Patente"	TEXT NOT NULL,
	"Marca"	TEXT NOT NULL,
	"Modelo"	TEXT NOT NULL,
	"Puertas"	INTEGER NOT NULL,
	"OwnerModelId"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
